name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  libcore:
    name: Native Build (LibCore)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Golang Status
        run: find buildScript libcore/*.sh | xargs cat | sha1sum > golang_status

      - name: Libcore Status
        run: git ls-files libcore | xargs cat | sha1sum > libcore_status

      - name: LibCore Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: app/libs/libcore.aar
          key: ${{ hashFiles('.github/workflows/*', 'golang_status', 'libcore_status') }}

      - name: Setup Go
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25
          cache-dependency-path: libcore/go.sum

      - name: Build LibCore
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./run lib core

  build:
    name: Build OSS Debug APK
    runs-on: ubuntu-latest
    needs: libcore
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Golang Status
        run: find buildScript libcore/*.sh | xargs cat | sha1sum > golang_status

      - name: Libcore Status
        run: git ls-files libcore | xargs cat | sha1sum > libcore_status

      - name: LibCore Cache
        uses: actions/cache@v4
        with:
          path: app/libs/libcore.aar
          key: ${{ hashFiles('.github/workflows/*', 'golang_status', 'libcore_status') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: gradle-build-${{ hashFiles('**/*.gradle.kts', 'gradle.properties', 'gradle/wrapper/gradle-wrapper.properties') }}

      - name: Prepare build environment
        env:
          BUILD_PLUGIN: none
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/25.0.8775105" >> local.properties
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./run init action gradle

      - name: Build APK
        run: ./gradlew app:assembleOssDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nekobox-oss-debug-apk
          path: app/build/outputs/apk/oss/debug/*.apk
